/** Checks whether a display name is still the auto-assigned default rather
 *  than one the player chose. */
export function isAutoGeneratedDisplayName(name?: string | null): boolean {
  if (!name || !name.trim()) return true;
  return name.trim().toLowerCase() === "player";
}

/** Required, 2–20 characters. */
export function validateDisplayNameFormat(name: string): { valid: boolean; error?: string } {
  const trimmed = name.trim();
  if (!trimmed) return { valid: false, error: "Display name is required" };
  if (trimmed.length < 2) return { valid: false, error: "Display name must be at least 2 characters" };
  if (trimmed.length > 20) return { valid: false, error: "Display name must be 20 characters or less" };
  return { valid: true };
}
